INSERT INTO Phones(Model, Brand, Description, Memory, Quantity, Price)
VALUES
('Iphone 11', 'Apple', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',256,100,1000),
('Galaxy s10','Samsung','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',128,60,800),
('Mi 9T Pro','Xiaomi','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',128,50,500),
('Iphone XR','Apple','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',64,25,500),
('Pixel 2','Goggle','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',128,68,450),
('Pixel 2 XL','Goggle','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',256,60,600),
('Honor 10','Honor','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',64,35,300),
('Mi 10','Xiaomi','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec volutpat est. Cras semper suscipit libero, in accumsan velit accumsan posuere. Maecenas fermentum quam eget augue fringilla, lacinia mattis libero semper. Suspendisse eget vehicula massa. Aenean sollicitudin eu erat a congue. Phasellus ut fermentum mi. Aliquam id justo lacinia, mollis ante id, tincidunt tellus. Pellentesque non felis viverra, convallis magna vitae, tempus lacus. Etiam aliquam vehicula porttitor. Praesent velit eros, feugiat eu ligula at, tristique pellentesque erat.',256,45,800);